services:
  - type: web
    name: student-fee-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/auth/login
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
