services:
  - type: web
    name: student-fee-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: APP_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://student-fee-management-pied.vercel.app
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
